name: Build and Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '14.x', '16.x' ]
    name: Node ${{ matrix.node-version }}
    steps:
      - name: Checkout project repository
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install global npm dependencies
        run: npm i -g jest
      - name: Install project npm dependencies
        run: npm ci
      - name: Build project
        run: npm run build
